// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=d8cf2cce42277b4298da0e6869831f73 file=mocks/mock_cfs_utstub.c
// Put manual extensions outside this directory; it is disposable.

// covmock: CFE_EVS_SendEvent already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_MSG_GetSize already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_AllocateMessageBuffer already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).

#include "cfe/modules/core_api/fsw/inc/cfe_msg.h"
#include "utgenstub.h"

// covmock: output-parameter handler for CFE_MSG_GetSize(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_MSG_GetSize(void *UserObj, UT_EntryKey_t FuncKey,
                                const UT_StubContext_t *Context)
{
    CFE_MSG_Size_t *Size = UT_Hook_GetArgValueByName(Context, "Size", CFE_MSG_Size_t *);

    (void)UserObj;
    (void)FuncKey;

    if (Size != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_MSG_GetSize), Size, sizeof(*Size));
    }
}
