// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=647788aa524607ac65071e779ae34c6f file=tests/test_CI_LAB_VerifyCmdLength.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_VerifyCmdLength_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_VerifyCmdLength_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "cfe.h"
#include "ci_lab_app.h"
#include "ci_lab_dispatch.h"
#include "ci_lab_cmds.h"
#include "ci_lab_msgids.h"
#include "mocks/mock_cfs_utstub.h"

// no declaring header was recorded for CI_LAB_VerifyCmdLength(const CFE_MSG_Message *, unsigned long); the declaration below was rebuilt from the analysed signature. Include the real header instead.
_Bool CI_LAB_VerifyCmdLength(const CFE_MSG_Message_t *, size_t);

// Mock backends contributing to this file: cfs-utstub
// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_VerifyCmdLength_covmock_Setup(void)
{
    UT_ResetState(UT_KEY(CFE_MSG_GetSize));
}

static void CI_LAB_VerifyCmdLength_covmock_length_matches(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_VerifyCmdLength_covmock_Register(void)
{
    UtTest_Add(CI_LAB_VerifyCmdLength_covmock_length_matches, CI_LAB_VerifyCmdLength_covmock_Setup, NULL, "length_matches");
}

// covmock case: length_matches
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_dispatch.c:37 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_dispatch.toml:1 covmock:test length_matches
// confidence: medium
// manifest id: 647788aa524607ac65071e779ae34c6f
// spec id: 93bcdb1855ed744d34c8de1722a4c524
static void CI_LAB_VerifyCmdLength_covmock_length_matches(void)
{
    CFE_MSG_Message_t Msg = {0};

    // arrange
    // A generated cFS stub copies nothing out of a data buffer by itself: the
    // copy happens in UT_Handler_CFE_MSG_GetSize, through UT_Stub_CopyToLocal. Both halves
    // are required, and the handler is registered here rather than named as the
    // stub's default, because a test-registered handler replaces a default one.
    {
        CFE_MSG_Size_t covmock_output_value = 0;

        UT_SetDataBuffer(UT_KEY(CFE_MSG_GetSize), &covmock_output_value,
                         sizeof(covmock_output_value), true);
        UT_SetHandlerFunction(UT_KEY(CFE_MSG_GetSize), UT_Handler_CFE_MSG_GetSize, NULL);
    }

    // act
    _Bool covmock_result = CI_LAB_VerifyCmdLength(&Msg, 0);
    (void)covmock_result;

    // assert
    UtAssert_True((covmock_result) == (true), "%s", "covmock_result == true");
}
