// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=3409b9d546ce92ab4a255bdd98943b34 file=mocks/mock_cfs_utstub.c
// Put manual extensions outside this directory; it is disposable.

// covmock: CFE_EVS_SendEvent already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_MSG_GetFcnCode already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_MSG_GetMsgId already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_MSG_GetSize already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_IsValidMsgId already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).

#include "apps/ci_lab/fsw/src/ci_lab_cmds.h"
#include "cfe/modules/core_api/fsw/inc/cfe_msg.h"
#include "utgenstub.h"

// covmock: generated stub for CI_LAB_NoopCmd()
CFE_Status_t CI_LAB_NoopCmd(const CI_LAB_NoopCmd_t *cmd)
{
    UT_GenStub_SetupReturnBuffer(CI_LAB_NoopCmd, CFE_Status_t);

    UT_GenStub_AddParam(CI_LAB_NoopCmd, const CI_LAB_NoopCmd_t *, cmd);

    UT_GenStub_Execute(CI_LAB_NoopCmd, Basic, NULL);

    return UT_GenStub_GetReturnValue(CI_LAB_NoopCmd, CFE_Status_t);
}

// covmock: generated stub for CI_LAB_ReadUplinkCmd()
CFE_Status_t CI_LAB_ReadUplinkCmd(const CI_LAB_ReadUplinkCmd_t *cmd)
{
    UT_GenStub_SetupReturnBuffer(CI_LAB_ReadUplinkCmd, CFE_Status_t);

    UT_GenStub_AddParam(CI_LAB_ReadUplinkCmd, const CI_LAB_ReadUplinkCmd_t *, cmd);

    UT_GenStub_Execute(CI_LAB_ReadUplinkCmd, Basic, NULL);

    return UT_GenStub_GetReturnValue(CI_LAB_ReadUplinkCmd, CFE_Status_t);
}

// covmock: generated stub for CI_LAB_ResetCountersCmd()
CFE_Status_t CI_LAB_ResetCountersCmd(const CI_LAB_ResetCountersCmd_t *cmd)
{
    UT_GenStub_SetupReturnBuffer(CI_LAB_ResetCountersCmd, CFE_Status_t);

    UT_GenStub_AddParam(CI_LAB_ResetCountersCmd, const CI_LAB_ResetCountersCmd_t *, cmd);

    UT_GenStub_Execute(CI_LAB_ResetCountersCmd, Basic, NULL);

    return UT_GenStub_GetReturnValue(CI_LAB_ResetCountersCmd, CFE_Status_t);
}

// covmock: generated stub for CI_LAB_SendHkCmd()
CFE_Status_t CI_LAB_SendHkCmd(const CI_LAB_SendHkCmd_t *cmd)
{
    UT_GenStub_SetupReturnBuffer(CI_LAB_SendHkCmd, CFE_Status_t);

    UT_GenStub_AddParam(CI_LAB_SendHkCmd, const CI_LAB_SendHkCmd_t *, cmd);

    UT_GenStub_Execute(CI_LAB_SendHkCmd, Basic, NULL);

    return UT_GenStub_GetReturnValue(CI_LAB_SendHkCmd, CFE_Status_t);
}

// covmock: output-parameter handler for CFE_MSG_GetFcnCode(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_MSG_GetFcnCode(void *UserObj, UT_EntryKey_t FuncKey,
                                   const UT_StubContext_t *Context)
{
    CFE_MSG_FcnCode_t *FcnCode = UT_Hook_GetArgValueByName(Context, "FcnCode", CFE_MSG_FcnCode_t *);

    (void)UserObj;
    (void)FuncKey;

    if (FcnCode != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_MSG_GetFcnCode), FcnCode, sizeof(*FcnCode));
    }
}

// covmock: output-parameter handler for CFE_MSG_GetMsgId(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_MSG_GetMsgId(void *UserObj, UT_EntryKey_t FuncKey,
                                 const UT_StubContext_t *Context)
{
    CFE_SB_MsgId_t *MsgId = UT_Hook_GetArgValueByName(Context, "MsgId", CFE_SB_MsgId_t *);

    (void)UserObj;
    (void)FuncKey;

    if (MsgId != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_MSG_GetMsgId), MsgId, sizeof(*MsgId));
    }
}

// covmock: output-parameter handler for CFE_MSG_GetSize(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_MSG_GetSize(void *UserObj, UT_EntryKey_t FuncKey,
                                const UT_StubContext_t *Context)
{
    CFE_MSG_Size_t *Size = UT_Hook_GetArgValueByName(Context, "Size", CFE_MSG_Size_t *);

    (void)UserObj;
    (void)FuncKey;

    if (Size != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_MSG_GetSize), Size, sizeof(*Size));
    }
}
