// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=66f38c8918a1c789876e11fcb5103c49 file=tests/test_CI_LAB_ResetCountersCmd.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_ResetCountersCmd_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_ResetCountersCmd_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "ci_lab_app.h"
#include "ci_lab_cmds.h"
#include "ci_lab_version.h"
#include "mocks/mock_cfs_utstub.h"

#include "apps/ci_lab/fsw/src/ci_lab_cmds.h"

// Mock backends contributing to this file: cfs-utstub
// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_ResetCountersCmd_covmock_Setup(void)
{
    UT_ResetState(UT_KEY(CFE_EVS_SendEvent));
    UT_ResetState(UT_KEY(CI_LAB_ResetCounters_Internal));
}

static void CI_LAB_ResetCountersCmd_covmock_reset_counters_reports(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_ResetCountersCmd_covmock_Register(void)
{
    UtTest_Add(CI_LAB_ResetCountersCmd_covmock_reset_counters_reports, CI_LAB_ResetCountersCmd_covmock_Setup, NULL, "reset_counters_reports");
}

// covmock case: reset_counters_reports
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_cmds.c:62 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_cmds.toml:2 covmock:test reset_counters_reports
// confidence: medium
// manifest id: 66f38c8918a1c789876e11fcb5103c49
// spec id: a84f0650a5bc9c0e7db23166ef4cf6a7
static void CI_LAB_ResetCountersCmd_covmock_reset_counters_reports(void)
{
    // act
    CFE_Status_t covmock_result = CI_LAB_ResetCountersCmd(NULL);
    (void)covmock_result;

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent))) == (1), "%s", "UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent)) == 1");
    UtAssert_True((UT_GetStubCount(UT_KEY(CI_LAB_ResetCounters_Internal))) == (1), "%s", "UT_GetStubCount(UT_KEY(CI_LAB_ResetCounters_Internal)) == 1");
    UtAssert_True((covmock_result) == (CFE_SUCCESS), "%s", "covmock_result == CFE_SUCCESS");
}
