// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=886fd2488093e8ec40a294f3b14b11b3 file=tests/test_CI_LAB_NoopCmd.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_NoopCmd_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_NoopCmd_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "ci_lab_app.h"
#include "ci_lab_cmds.h"
#include "ci_lab_version.h"
#include "mocks/mock_cfs_utstub.h"

#include "apps/ci_lab/fsw/src/ci_lab_cmds.h"

// Mock backends contributing to this file: cfs-utstub
// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_NoopCmd_covmock_Setup(void)
{
    UT_ResetState(UT_KEY(CFE_EVS_SendEvent));
}

static void CI_LAB_NoopCmd_covmock_noop_counts_and_reports(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_NoopCmd_covmock_Register(void)
{
    UtTest_Add(CI_LAB_NoopCmd_covmock_noop_counts_and_reports, CI_LAB_NoopCmd_covmock_Setup, NULL, "noop_counts_and_reports");
}

// covmock case: noop_counts_and_reports
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_cmds.c:41 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_cmds.toml:1 covmock:test noop_counts_and_reports
// confidence: medium
// manifest id: 886fd2488093e8ec40a294f3b14b11b3
// spec id: bdc02a47bc2e17245c8b3418fd9c52bf
static void CI_LAB_NoopCmd_covmock_noop_counts_and_reports(void)
{
    // act
    CFE_Status_t covmock_result = CI_LAB_NoopCmd(NULL);
    (void)covmock_result;

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent))) == (1), "%s", "UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent)) == 1");
    UtAssert_True((covmock_result) == (CFE_SUCCESS), "%s", "covmock_result == CFE_SUCCESS");
}
