// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=a73ea26757fa2f115639ecda8cc00f24 file=tests/test_CI_LAB_TaskInit.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_TaskInit_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_TaskInit_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "ci_lab_app.h"
#include "ci_lab_perfids.h"
#include "ci_lab_msgids.h"
#include "ci_lab_version.h"
#include "ci_lab_decode.h"
#include "mocks/mock_cfs_utstub.h"

#include "apps/ci_lab/fsw/src/ci_lab_app.h"

// Mock backends contributing to this file: cfs-utstub
// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_TaskInit_covmock_Setup(void)
{
    UT_ResetState(UT_KEY(CFE_ES_WriteToSysLog));
    UT_ResetState(UT_KEY(CFE_EVS_Register));
    UT_ResetState(UT_KEY(CFE_EVS_SendEvent));
    UT_ResetState(UT_KEY(CFE_SB_CreatePipe));
    UT_ResetState(UT_KEY(CFE_SB_Subscribe));
    UT_ResetState(UT_KEY(OS_SocketBind));
    UT_ResetState(UT_KEY(OS_SocketOpen));
}

static void CI_LAB_TaskInit_covmock_init_reports_every_registration_failure(void);
static void CI_LAB_TaskInit_covmock_init_reports_pipe_and_bind_failures(void);
static void CI_LAB_TaskInit_covmock_init_subscribes_and_binds(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_TaskInit_covmock_Register(void)
{
    UtTest_Add(CI_LAB_TaskInit_covmock_init_reports_every_registration_failure, CI_LAB_TaskInit_covmock_Setup, NULL, "init_reports_every_registration_failure");
    UtTest_Add(CI_LAB_TaskInit_covmock_init_reports_pipe_and_bind_failures, CI_LAB_TaskInit_covmock_Setup, NULL, "init_reports_pipe_and_bind_failures");
    UtTest_Add(CI_LAB_TaskInit_covmock_init_subscribes_and_binds, CI_LAB_TaskInit_covmock_Setup, NULL, "init_subscribes_and_binds");
}

// covmock case: init_reports_every_registration_failure
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_app.c:116 (line, line_executed)
// condition: status != CFE_SUCCESS
// requirements: CI-INIT-ERR
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_app.toml:5 covmock:test init_reports_every_registration_failure
// confidence: medium
// manifest id: a73ea26757fa2f115639ecda8cc00f24
// spec id: 9a24062c0b1c63daa987b425e01348c2
static void CI_LAB_TaskInit_covmock_init_reports_every_registration_failure(void)
{
    // TODO(covmock): READINESS: placeholder arrangement: missing exact_constraint. The slice, endpoints and constraint above say what is known; what is missing needs an annotation, an adapter, or an engineer.

    // arrange
    UT_SetDefaultReturnValue(UT_KEY(CFE_EVS_Register), -1);
    UT_SetDefaultReturnValue(UT_KEY(CFE_SB_Subscribe), -1);
    UT_SetDefaultReturnValue(UT_KEY(OS_SocketOpen), -1);

    // act
    CI_LAB_TaskInit();

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_ES_WriteToSysLog))) == (1), "%s", "UT_GetStubCount(UT_KEY(CFE_ES_WriteToSysLog)) == 1");
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent))) == (5), "%s", "UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent)) == 5");
    UtAssert_True((UT_GetStubCount(UT_KEY(OS_SocketBind))) == (0), "%s", "UT_GetStubCount(UT_KEY(OS_SocketBind)) == 0");
}

// covmock case: init_reports_pipe_and_bind_failures
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_app.c:151 (line, line_executed)
// condition: status == CFE_SUCCESS
// requirements: CI-INIT-ERR
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_app.toml:6 covmock:test init_reports_pipe_and_bind_failures
// confidence: medium
// manifest id: a73ea26757fa2f115639ecda8cc00f24
// spec id: 5ca3631f9fe168535572c7436f6f1bb8
static void CI_LAB_TaskInit_covmock_init_reports_pipe_and_bind_failures(void)
{
    // TODO(covmock): READINESS: placeholder arrangement: missing exact_constraint. The slice, endpoints and constraint above say what is known; what is missing needs an annotation, an adapter, or an engineer.

    // arrange
    UT_SetDefaultReturnValue(UT_KEY(CFE_SB_CreatePipe), -1);
    UT_SetDefaultReturnValue(UT_KEY(OS_SocketBind), -1);

    // act
    CI_LAB_TaskInit();

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent))) == (3), "%s", "UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent)) == 3");
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_SB_Subscribe))) == (0), "%s", "UT_GetStubCount(UT_KEY(CFE_SB_Subscribe)) == 0");
}

// covmock case: init_subscribes_and_binds
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_app.c:109 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_app.toml:3 covmock:test init_subscribes_and_binds
// confidence: medium
// manifest id: a73ea26757fa2f115639ecda8cc00f24
// spec id: e01baf729c63c229135d6534de10ea04
static void CI_LAB_TaskInit_covmock_init_subscribes_and_binds(void)
{
    // act
    CI_LAB_TaskInit();

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent))) == (1), "%s", "UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent)) == 1");
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_SB_Subscribe))) == (3), "%s", "UT_GetStubCount(UT_KEY(CFE_SB_Subscribe)) == 3");
    UtAssert_True((UT_GetStubCount(UT_KEY(OS_SocketBind))) == (1), "%s", "UT_GetStubCount(UT_KEY(OS_SocketBind)) == 1");
}
