// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=a73ea26757fa2f115639ecda8cc00f24 file=tests/test_CI_LAB_AppMain.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_AppMain_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_AppMain_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "ci_lab_app.h"
#include "ci_lab_perfids.h"
#include "ci_lab_msgids.h"
#include "ci_lab_version.h"
#include "ci_lab_decode.h"
#include "mocks/mock_cfs_utstub.h"

#include "apps/ci_lab/fsw/src/ci_lab_app.h"

// Mock backends contributing to this file: cfs-utstub
// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_AppMain_covmock_Setup(void)
{
    UT_ResetState(UT_KEY(CFE_ES_ExitApp));
    UT_ResetState(UT_KEY(CFE_ES_RunLoop));
    UT_ResetState(UT_KEY(CFE_SB_ReceiveBuffer));
    UT_ResetState(UT_KEY(CI_LAB_TaskPipe));
    UT_ResetState(UT_KEY(OS_SocketBind));
    UT_ResetState(UT_KEY(OS_SocketRecvFrom));
}

static void CI_LAB_AppMain_covmock_main_runs_one_cycle_then_exits(void);
static void CI_LAB_AppMain_covmock_main_skips_pipe_and_uplink_on_errors(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_AppMain_covmock_Register(void)
{
    UtTest_Add(CI_LAB_AppMain_covmock_main_runs_one_cycle_then_exits, CI_LAB_AppMain_covmock_Setup, NULL, "main_runs_one_cycle_then_exits");
    UtTest_Add(CI_LAB_AppMain_covmock_main_skips_pipe_and_uplink_on_errors, CI_LAB_AppMain_covmock_Setup, NULL, "main_skips_pipe_and_uplink_on_errors");
}

// covmock case: main_runs_one_cycle_then_exits
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_app.c:53 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_app.toml:1 covmock:test main_runs_one_cycle_then_exits
// confidence: medium
// manifest id: a73ea26757fa2f115639ecda8cc00f24
// spec id: c212d1ae90bea1266aa60a0f265b68a9
static void CI_LAB_AppMain_covmock_main_runs_one_cycle_then_exits(void)
{
    // arrange
    // cFS consumes deferred return codes in the order they are added, each one
    // the given number of calls after its predecessor -- so a per-call sequence
    // is a count of 1 on every entry, not the call number.
    UT_SetDeferredRetcode(UT_KEY(CFE_ES_RunLoop), 1, true);
    UT_SetDeferredRetcode(UT_KEY(CFE_ES_RunLoop), 1, false);

    // act
    CI_LAB_AppMain();

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_ES_ExitApp))) == (1), "%s", "UT_GetStubCount(UT_KEY(CFE_ES_ExitApp)) == 1");
    UtAssert_True((UT_GetStubCount(UT_KEY(CI_LAB_TaskPipe))) == (1), "%s", "UT_GetStubCount(UT_KEY(CI_LAB_TaskPipe)) == 1");
}

// covmock case: main_skips_pipe_and_uplink_on_errors
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_app.c:56 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_app.toml:7 covmock:test main_skips_pipe_and_uplink_on_errors
// confidence: medium
// manifest id: a73ea26757fa2f115639ecda8cc00f24
// spec id: 6c47654f4ffeb085e6b1f9dcab45c573
static void CI_LAB_AppMain_covmock_main_skips_pipe_and_uplink_on_errors(void)
{
    // arrange
    // cFS consumes deferred return codes in the order they are added, each one
    // the given number of calls after its predecessor -- so a per-call sequence
    // is a count of 1 on every entry, not the call number.
    UT_SetDeferredRetcode(UT_KEY(CFE_ES_RunLoop), 1, true);
    UT_SetDeferredRetcode(UT_KEY(CFE_ES_RunLoop), 1, false);
    UT_SetDefaultReturnValue(UT_KEY(CFE_SB_ReceiveBuffer), -1);
    UT_SetDefaultReturnValue(UT_KEY(OS_SocketBind), -1);

    // act
    CI_LAB_AppMain();

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_ES_ExitApp))) == (1), "%s", "UT_GetStubCount(UT_KEY(CFE_ES_ExitApp)) == 1");
    UtAssert_True((UT_GetStubCount(UT_KEY(CI_LAB_TaskPipe))) == (0), "%s", "UT_GetStubCount(UT_KEY(CI_LAB_TaskPipe)) == 0");
    UtAssert_True((UT_GetStubCount(UT_KEY(OS_SocketRecvFrom))) == (0), "%s", "UT_GetStubCount(UT_KEY(OS_SocketRecvFrom)) == 0");
}
