// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=e766d802c8bf031c7212adc3e4e8ae13 file=tests/test_CI_LAB_delete_callback.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_delete_callback_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_delete_callback_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "ci_lab_app.h"
#include "ci_lab_perfids.h"
#include "ci_lab_msgids.h"
#include "ci_lab_version.h"
#include "ci_lab_decode.h"
#include "mocks/mock_cfs_utstub.h"

// no declaring header was recorded for CI_LAB_delete_callback(); the declaration below was rebuilt from the analysed signature. Include the real header instead.
void CI_LAB_delete_callback(void);

// Mock backends contributing to this file: cfs-utstub
// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_delete_callback_covmock_Setup(void)
{
    UT_ResetState(UT_KEY(OS_close));
}

static void CI_LAB_delete_callback_covmock_delete_callback_closes_socket(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_delete_callback_covmock_Register(void)
{
    UtTest_Add(CI_LAB_delete_callback_covmock_delete_callback_closes_socket, CI_LAB_delete_callback_covmock_Setup, NULL, "delete_callback_closes_socket");
}

// covmock case: delete_callback_closes_socket
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_app.c:94 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_app.toml:2 covmock:test delete_callback_closes_socket
// confidence: medium
// manifest id: e766d802c8bf031c7212adc3e4e8ae13
// spec id: 95f2aca9a7f99899bd9914b79bc3e86e
static void CI_LAB_delete_callback_covmock_delete_callback_closes_socket(void)
{
    // act
    CI_LAB_delete_callback();

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(OS_close))) == (1), "%s", "UT_GetStubCount(UT_KEY(OS_close)) == 1");
}
