// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=e766d802c8bf031c7212adc3e4e8ae13 file=tests/test_CI_LAB_ReadUpLink.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_ReadUpLink_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_ReadUpLink_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "ci_lab_app.h"
#include "ci_lab_perfids.h"
#include "ci_lab_msgids.h"
#include "ci_lab_version.h"
#include "ci_lab_decode.h"
#include "mocks/mock_cfs_utstub.h"

#include "apps/ci_lab/fsw/src/ci_lab_app.h"

// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_ReadUpLink_covmock_Setup(void)
{
    // no per-case arrangement state to reset
}

static void CI_LAB_ReadUpLink_covmock_read_uplink_stops_without_a_buffer(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_ReadUpLink_covmock_Register(void)
{
    UtTest_Add(CI_LAB_ReadUpLink_covmock_read_uplink_stops_without_a_buffer, CI_LAB_ReadUpLink_covmock_Setup, NULL, "read_uplink_stops_without_a_buffer");
}

// covmock case: read_uplink_stops_without_a_buffer
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_app.c:243 (line, line_executed)
// condition: CI_LAB_Global . NetBufPtr == NULL
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_app.toml:4 covmock:test read_uplink_stops_without_a_buffer
// confidence: none
// manifest id: e766d802c8bf031c7212adc3e4e8ae13
// spec id: f4277d4c5fc546f6cc9c46bbda27b3aa
static void CI_LAB_ReadUpLink_covmock_read_uplink_stops_without_a_buffer(void)
{
    // TODO(covmock): AMBIGUOUS_ARRANGEMENT: 2 arrangements claim c:@F@CFE_ES_PerfLogAdd unsupported: covmock keeps all of them and chooses between none, because an annotation naming that slot cannot say which one it means (Two solutions for one slot is an analysis result worth reporting; until it is resolved, review the generated arrangements for this seam by hand.)
    // TODO(covmock): AMBIGUOUS_ARRANGEMENT: 2 arrangements claim c:@F@CFE_SB_TransmitBuffer unsupported: covmock keeps all of them and chooses between none, because an annotation naming that slot cannot say which one it means (Two solutions for one slot is an analysis result worth reporting; until it is resolved, review the generated arrangements for this seam by hand.)
    // TODO(covmock): AMBIGUOUS_ARRANGEMENT: 2 arrangements claim c:@F@CI_LAB_DecodeInputMessage unsupported: covmock keeps all of them and chooses between none, because an annotation naming that slot cannot say which one it means (Two solutions for one slot is an analysis result worth reporting; until it is resolved, review the generated arrangements for this seam by hand.)
    // TODO(covmock): AMBIGUOUS_ARRANGEMENT: 2 arrangements claim c:@F@OS_SocketRecvFrom unsupported: covmock keeps all of them and chooses between none, because an annotation naming that slot cannot say which one it means (Two solutions for one slot is an analysis result worth reporting; until it is resolved, review the generated arrangements for this seam by hand.)
    // TODO(covmock): LOOP_CARRIED_REQUIREMENT: reaching the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 with the required value needs `CI_LAB_Global . NetBufPtr == NULL` is false on a loop condition the path re-evaluates; the analysis does not unroll the loop or guess how many iterations run.
    // TODO(covmock): LOOP_CARRIED_REQUIREMENT: reaching the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 with the required value needs `CI_LAB_Global . NetBufPtr == NULL` is true on a loop condition the path re-evaluates; the analysis does not unroll the loop or guess how many iterations run.
    // TODO(covmock): LOOP_CARRIED_REQUIREMENT: reaching the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 with the required value needs `CfeStatus != CFE_SUCCESS` is false on a loop condition the path re-evaluates; the analysis does not unroll the loop or guess how many iterations run.
    // TODO(covmock): LOOP_CARRIED_REQUIREMENT: reaching the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 with the required value needs `CfeStatus == CFE_SUCCESS` is false on a loop condition the path re-evaluates; the analysis does not unroll the loop or guess how many iterations run.
    // TODO(covmock): LOOP_CARRIED_REQUIREMENT: reaching the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 with the required value needs `CfeStatus == CFE_SUCCESS` is true on a loop condition the path re-evaluates; the analysis does not unroll the loop or guess how many iterations run.
    // TODO(covmock): LOOP_CARRIED_REQUIREMENT: reaching the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 with the required value needs `OsStatus > 0` is true on a loop condition the path re-evaluates; the analysis does not unroll the loop or guess how many iterations run.
    // TODO(covmock): LOOP_CARRIED_REQUIREMENT: reaching the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 with the required value needs `i <= CI_LAB_PLATFORM_MAX_INGEST_PKTS` is true on a loop condition the path re-evaluates; the analysis does not unroll the loop or guess how many iterations run.
    // TODO(covmock): NO_CONTROLLABLE_SEAM: the slice from the if at apps/ci_lab/fsw/src/ci_lab_app.c:241:13 ends at 9 endpoint(s) no test can arrange: unknown: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee; unknown: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee; unknown: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee; unknown: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee; unknown: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here; unknown: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee; unknown: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here; unknown: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee; unknown: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here. A fake for such a symbol would link and run without intercepting anything; an adapter recommendation is M5's.
    // TODO(covmock): READINESS: placeholder arrangement: missing complete_slice_to_controllable_seam, control_requirements_modelled. The slice, endpoints and constraint above say what is known; what is missing needs an annotation, an adapter, or an engineer.
    // TODO(covmock): UNKNOWN_CALL_EFFECT: 'CI_LAB_Global.NetBufPtr' may be defined by a write to unknown memory: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here
    // TODO(covmock): UNKNOWN_CALL_EFFECT: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee
    // TODO(covmock): UNKNOWN_CALL_EFFECT: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr': its address is passed to a call whose parameter is a non-const pointer; the callee may or may not write it, so this is a may-definition beside the earlier ones
    // TODO(covmock): no registered mock backend claimed seam CFE_ES_PerfLogAdd (c:@F@CFE_ES_PerfLogAdd), so its unsupported arrangement was not rendered
    // TODO(covmock): no registered mock backend claimed seam CFE_EVS_SendEvent (c:@F@CFE_EVS_SendEvent), so its unsupported arrangement was not rendered
    // TODO(covmock): no registered mock backend claimed seam CFE_SB_TransmitBuffer (c:@F@CFE_SB_TransmitBuffer), so its unsupported arrangement was not rendered
    // TODO(covmock): no registered mock backend claimed seam CI_LAB_DecodeInputMessage (c:@F@CI_LAB_DecodeInputMessage), so its unsupported arrangement was not rendered
    // TODO(covmock): no registered mock backend claimed seam CI_LAB_GetInputBuffer (c:@F@CI_LAB_GetInputBuffer), so its output_parameter_value arrangement was not rendered
    // TODO(covmock): no registered mock backend claimed seam CI_LAB_Global.NetBufPtr (sha256:06e7c3b559678c022cd77ae0df175f05517e9ff32501765429c62134769f5878), so its unsupported arrangement was not rendered
    // TODO(covmock): no registered mock backend claimed seam OS_SocketRecvFrom (c:@F@OS_SocketRecvFrom), so its unsupported arrangement was not rendered
    // TODO(covmock): seam CFE_ES_PerfLogAdd (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported CFE_ES_PerfLogAdd as not controllable: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee
    // TODO(covmock): seam CFE_EVS_SendEvent (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported CFE_EVS_SendEvent as not controllable: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee
    // TODO(covmock): seam CFE_SB_TransmitBuffer (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported CFE_SB_TransmitBuffer as not controllable: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here
    // TODO(covmock): seam CFE_SB_TransmitBuffer (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported CFE_SB_TransmitBuffer as not controllable: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee
    // TODO(covmock): seam CI_LAB_DecodeInputMessage (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported CI_LAB_DecodeInputMessage as not controllable: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here
    // TODO(covmock): seam CI_LAB_DecodeInputMessage (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported CI_LAB_DecodeInputMessage as not controllable: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee
    // TODO(covmock): seam CI_LAB_GetInputBuffer (output_parameter) cannot be controlled: BACKEND_NOT_IMPLEMENTED -- backend 'cfs-utstub' was requested but cannot render CI_LAB_GetInputBuffer.
    // TODO(covmock): seam OS_SocketRecvFrom (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported OS_SocketRecvFrom as not controllable: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here: 'CI_LAB_Global.NetBufPtr' may be the unknown memory written here
    // TODO(covmock): seam OS_SocketRecvFrom (external_function) cannot be controlled: NO_CONTROLLABLE_SEAM -- the analyzer reported OS_SocketRecvFrom as not controllable: 'CI_LAB_Global.NetBufPtr' may be written by a call with no summary: 'CI_LAB_Global.NetBufPtr' may be written by the call: no summary describes the callee

    // act
    CI_LAB_ReadUpLink();

    // assert
    // TODO(covmock): expect call_count_equals on CI_LAB_GetInputBuffer: no assertion could be rendered without inventing a value or a comparison, so none was
    // TODO(covmock): expect call_count_equals on OS_SocketRecvFrom: no assertion could be rendered without inventing a value or a comparison, so none was
}
