// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=a73ea26757fa2f115639ecda8cc00f24 file=mocks/mock_cfs_utstub.c
// Put manual extensions outside this directory; it is disposable.

// covmock: CFE_ES_ExitApp already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_ES_RunLoop already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_ES_WriteToSysLog already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_EVS_Register already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_EVS_SendEvent already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_CreatePipe already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_ReceiveBuffer already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_Subscribe already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CI_LAB_TaskPipe already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketBind already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketOpen already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketRecvFrom already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_close already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).

#include "cfe/modules/core_api/fsw/inc/cfe_es.h"
#include "cfe/modules/core_api/fsw/inc/cfe_sb.h"
#include "osal/src/os/inc/osapi-sockets.h"
#include "utgenstub.h"

// covmock: output-parameter handler for CFE_ES_RunLoop(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_ES_RunLoop(void *UserObj, UT_EntryKey_t FuncKey,
                               const UT_StubContext_t *Context)
{
    uint32 *RunStatus = UT_Hook_GetArgValueByName(Context, "RunStatus", uint32 *);

    (void)UserObj;
    (void)FuncKey;

    if (RunStatus != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_ES_RunLoop), RunStatus, sizeof(*RunStatus));
    }
}

// covmock: output-parameter handler for CFE_SB_CreatePipe(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_SB_CreatePipe(void *UserObj, UT_EntryKey_t FuncKey,
                                  const UT_StubContext_t *Context)
{
    CFE_SB_PipeId_t *PipeIdPtr = UT_Hook_GetArgValueByName(Context, "PipeIdPtr", CFE_SB_PipeId_t *);

    (void)UserObj;
    (void)FuncKey;

    if (PipeIdPtr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_SB_CreatePipe), PipeIdPtr, sizeof(*PipeIdPtr));
    }
}

// covmock: output-parameter handler for CFE_SB_ReceiveBuffer(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_SB_ReceiveBuffer(void *UserObj, UT_EntryKey_t FuncKey,
                                     const UT_StubContext_t *Context)
{
    CFE_SB_Buffer_t **BufPtr = UT_Hook_GetArgValueByName(Context, "BufPtr", CFE_SB_Buffer_t **);

    (void)UserObj;
    (void)FuncKey;

    if (BufPtr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_SB_ReceiveBuffer), BufPtr, sizeof(*BufPtr));
    }
}

// covmock: output-parameter handler for OS_SocketOpen(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_OS_SocketOpen(void *UserObj, UT_EntryKey_t FuncKey,
                              const UT_StubContext_t *Context)
{
    osal_id_t *sock_id = UT_Hook_GetArgValueByName(Context, "sock_id", osal_id_t *);

    (void)UserObj;
    (void)FuncKey;

    if (sock_id != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(OS_SocketOpen), sock_id, sizeof(*sock_id));
    }
}

// covmock: output-parameter handler for OS_SocketRecvFrom(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_OS_SocketRecvFrom(void *UserObj, UT_EntryKey_t FuncKey,
                                  const UT_StubContext_t *Context)
{
    OS_SockAddr_t *RemoteAddr = UT_Hook_GetArgValueByName(Context, "RemoteAddr", OS_SockAddr_t *);

    (void)UserObj;
    (void)FuncKey;

    if (RemoteAddr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(OS_SocketRecvFrom), RemoteAddr, sizeof(*RemoteAddr));
    }
}
