// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=e766d802c8bf031c7212adc3e4e8ae13 file=mocks/mock_cfs_utstub.c
// Put manual extensions outside this directory; it is disposable.

// covmock: CFE_Config_GetVersionString already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_ES_ExitApp already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_ES_PerfLogAdd already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_ES_RunLoop already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_ES_WriteToSysLog already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_EVS_Register already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_EVS_SendEvent already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_MSG_Init already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_PSP_GetProcessorId already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_CreatePipe already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_ReceiveBuffer already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_Subscribe already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_TransmitBuffer already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketAddrInit already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketAddrSetPort already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketBind already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketOpen already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_SocketRecvFrom already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_TaskInstallDeleteHandler already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_close already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: OS_printf already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).

#include "apps/ci_lab/fsw/src/ci_lab_decode.h"
#include "apps/ci_lab/fsw/src/ci_lab_dispatch.h"
#include "cfe/modules/core_api/fsw/inc/cfe_config.h"
#include "cfe/modules/core_api/fsw/inc/cfe_es.h"
#include "cfe/modules/core_api/fsw/inc/cfe_msg.h"
#include "cfe/modules/core_api/fsw/inc/cfe_sb.h"
#include "osal/src/os/inc/osapi-sockets.h"
#include "utgenstub.h"

// covmock: generated stub for CI_LAB_DecodeInputMessage()
CFE_Status_t CI_LAB_DecodeInputMessage(void *SourceBuffer, size_t SourceSize, CFE_SB_Buffer_t **DestBufferOut)
{
    UT_GenStub_SetupReturnBuffer(CI_LAB_DecodeInputMessage, CFE_Status_t);

    UT_GenStub_AddParam(CI_LAB_DecodeInputMessage, void *, SourceBuffer);
    UT_GenStub_AddParam(CI_LAB_DecodeInputMessage, size_t, SourceSize);
    UT_GenStub_AddParam(CI_LAB_DecodeInputMessage, CFE_SB_Buffer_t **, DestBufferOut);

    UT_GenStub_Execute(CI_LAB_DecodeInputMessage, Basic, NULL);

    return UT_GenStub_GetReturnValue(CI_LAB_DecodeInputMessage, CFE_Status_t);
}

// covmock: generated stub for CI_LAB_GetInputBuffer()
CFE_Status_t CI_LAB_GetInputBuffer(void **BufferOut, size_t *SizeOut)
{
    UT_GenStub_SetupReturnBuffer(CI_LAB_GetInputBuffer, CFE_Status_t);

    UT_GenStub_AddParam(CI_LAB_GetInputBuffer, void **, BufferOut);
    UT_GenStub_AddParam(CI_LAB_GetInputBuffer, size_t *, SizeOut);

    UT_GenStub_Execute(CI_LAB_GetInputBuffer, Basic, NULL);

    return UT_GenStub_GetReturnValue(CI_LAB_GetInputBuffer, CFE_Status_t);
}

// covmock: generated stub for CI_LAB_TaskPipe()
void CI_LAB_TaskPipe(const CFE_SB_Buffer_t *SBBufPtr)
{
    UT_GenStub_AddParam(CI_LAB_TaskPipe, const CFE_SB_Buffer_t *, SBBufPtr);

    UT_GenStub_Execute(CI_LAB_TaskPipe, Basic, NULL);
}

// covmock: output-parameter handler for CFE_Config_GetVersionString(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_Config_GetVersionString(void *UserObj, UT_EntryKey_t FuncKey,
                                            const UT_StubContext_t *Context)
{
    char *Buf = UT_Hook_GetArgValueByName(Context, "Buf", char *);

    (void)UserObj;
    (void)FuncKey;

    if (Buf != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_Config_GetVersionString), Buf, sizeof(*Buf));
    }
}

// covmock: output-parameter handler for CFE_ES_RunLoop(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_ES_RunLoop(void *UserObj, UT_EntryKey_t FuncKey,
                               const UT_StubContext_t *Context)
{
    uint32 *RunStatus = UT_Hook_GetArgValueByName(Context, "RunStatus", uint32 *);

    (void)UserObj;
    (void)FuncKey;

    if (RunStatus != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_ES_RunLoop), RunStatus, sizeof(*RunStatus));
    }
}

// covmock: output-parameter handler for CFE_MSG_Init(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_MSG_Init(void *UserObj, UT_EntryKey_t FuncKey,
                             const UT_StubContext_t *Context)
{
    CFE_MSG_Message_t *MsgPtr = UT_Hook_GetArgValueByName(Context, "MsgPtr", CFE_MSG_Message_t *);

    (void)UserObj;
    (void)FuncKey;

    if (MsgPtr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_MSG_Init), MsgPtr, sizeof(*MsgPtr));
    }
}

// covmock: output-parameter handler for CFE_SB_CreatePipe(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_SB_CreatePipe(void *UserObj, UT_EntryKey_t FuncKey,
                                  const UT_StubContext_t *Context)
{
    CFE_SB_PipeId_t *PipeIdPtr = UT_Hook_GetArgValueByName(Context, "PipeIdPtr", CFE_SB_PipeId_t *);

    (void)UserObj;
    (void)FuncKey;

    if (PipeIdPtr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_SB_CreatePipe), PipeIdPtr, sizeof(*PipeIdPtr));
    }
}

// covmock: output-parameter handler for CFE_SB_ReceiveBuffer(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_SB_ReceiveBuffer(void *UserObj, UT_EntryKey_t FuncKey,
                                     const UT_StubContext_t *Context)
{
    CFE_SB_Buffer_t **BufPtr = UT_Hook_GetArgValueByName(Context, "BufPtr", CFE_SB_Buffer_t **);

    (void)UserObj;
    (void)FuncKey;

    if (BufPtr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_SB_ReceiveBuffer), BufPtr, sizeof(*BufPtr));
    }
}

// covmock: output-parameter handler for CFE_SB_TransmitBuffer(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_SB_TransmitBuffer(void *UserObj, UT_EntryKey_t FuncKey,
                                      const UT_StubContext_t *Context)
{
    CFE_SB_Buffer_t *BufPtr = UT_Hook_GetArgValueByName(Context, "BufPtr", CFE_SB_Buffer_t *);

    (void)UserObj;
    (void)FuncKey;

    if (BufPtr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_SB_TransmitBuffer), BufPtr, sizeof(*BufPtr));
    }
}

// covmock: output-parameter handler for CI_LAB_DecodeInputMessage(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CI_LAB_DecodeInputMessage(void *UserObj, UT_EntryKey_t FuncKey,
                                          const UT_StubContext_t *Context)
{
    CFE_SB_Buffer_t **DestBufferOut = UT_Hook_GetArgValueByName(Context, "DestBufferOut", CFE_SB_Buffer_t **);

    (void)UserObj;
    (void)FuncKey;

    if (DestBufferOut != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CI_LAB_DecodeInputMessage), DestBufferOut, sizeof(*DestBufferOut));
    }
}

// covmock: output-parameter handler for OS_SocketAddrInit(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_OS_SocketAddrInit(void *UserObj, UT_EntryKey_t FuncKey,
                                  const UT_StubContext_t *Context)
{
    OS_SockAddr_t *Addr = UT_Hook_GetArgValueByName(Context, "Addr", OS_SockAddr_t *);

    (void)UserObj;
    (void)FuncKey;

    if (Addr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(OS_SocketAddrInit), Addr, sizeof(*Addr));
    }
}

// covmock: output-parameter handler for OS_SocketAddrSetPort(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_OS_SocketAddrSetPort(void *UserObj, UT_EntryKey_t FuncKey,
                                     const UT_StubContext_t *Context)
{
    OS_SockAddr_t *Addr = UT_Hook_GetArgValueByName(Context, "Addr", OS_SockAddr_t *);

    (void)UserObj;
    (void)FuncKey;

    if (Addr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(OS_SocketAddrSetPort), Addr, sizeof(*Addr));
    }
}

// covmock: output-parameter handler for OS_SocketOpen(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_OS_SocketOpen(void *UserObj, UT_EntryKey_t FuncKey,
                              const UT_StubContext_t *Context)
{
    osal_id_t *sock_id = UT_Hook_GetArgValueByName(Context, "sock_id", osal_id_t *);

    (void)UserObj;
    (void)FuncKey;

    if (sock_id != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(OS_SocketOpen), sock_id, sizeof(*sock_id));
    }
}

// covmock: output-parameter handler for OS_SocketRecvFrom(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_OS_SocketRecvFrom(void *UserObj, UT_EntryKey_t FuncKey,
                                  const UT_StubContext_t *Context)
{
    OS_SockAddr_t *RemoteAddr = UT_Hook_GetArgValueByName(Context, "RemoteAddr", OS_SockAddr_t *);

    (void)UserObj;
    (void)FuncKey;

    if (RemoteAddr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(OS_SocketRecvFrom), RemoteAddr, sizeof(*RemoteAddr));
    }
}
