// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=e766d802c8bf031c7212adc3e4e8ae13 file=mocks/mock_cfs_utstub.h
// Put manual extensions outside this directory; it is disposable.

#ifdef __cplusplus
extern "C" {
#endif

#include "apps/ci_lab/fsw/src/ci_lab_decode.h"
#include "apps/ci_lab/fsw/src/ci_lab_dispatch.h"
#include "cfe/modules/core_api/fsw/inc/cfe_config.h"
#include "cfe/modules/core_api/fsw/inc/cfe_es.h"
#include "cfe/modules/core_api/fsw/inc/cfe_evs.h"
#include "cfe/modules/core_api/fsw/inc/cfe_msg.h"
#include "cfe/modules/core_api/fsw/inc/cfe_sb.h"
#include "osal/src/os/inc/osapi-file.h"
#include "osal/src/os/inc/osapi-printf.h"
#include "osal/src/os/inc/osapi-sockets.h"
#include "osal/src/os/inc/osapi-task.h"
#include "psp/fsw/inc/cfe_psp_id_api.h"
#include "utstubs.h"

// covmock: a cFS stub is a definition of the production prototype, so
// nothing is declared here -- the production header above already
// declares every stubbed function, and utstubs.h supplies
// UT_KEY() and the UT_Set*/UT_Get* control API a test arranges with.

// covmock: the output-parameter handlers (#100). A generated stub copies
// nothing out of a data buffer by itself -- the copy happens in a handler --
// so the arrangement installs one of these, and it is declared here because
// the arrangement is written in the test's translation unit, not in the mock's.
void UT_Handler_CFE_Config_GetVersionString(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_CFE_ES_RunLoop(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_CFE_MSG_Init(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_CFE_SB_CreatePipe(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_CFE_SB_ReceiveBuffer(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_CFE_SB_TransmitBuffer(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_CI_LAB_DecodeInputMessage(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_OS_SocketAddrInit(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_OS_SocketAddrSetPort(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_OS_SocketOpen(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);
void UT_Handler_OS_SocketRecvFrom(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);

#ifdef __cplusplus
}  // extern "C"
#endif
