// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=ce1819b382f0b79e44ddd50593536656 file=tests/test_CI_LAB_GetInputBuffer.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_GetInputBuffer_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_GetInputBuffer_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "cfe.h"
#include "ci_lab_app.h"
#include "ci_lab_perfids.h"
#include "ci_lab_msgids.h"
#include "ci_lab_decode.h"
#include "mocks/mock_cfs_utstub.h"

#include "apps/ci_lab/fsw/src/ci_lab_decode.h"

// Mock backends contributing to this file: cfs-utstub
// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_GetInputBuffer_covmock_Setup(void)
{
    UT_ResetState(UT_KEY(CFE_SB_AllocateMessageBuffer));
}

static void CI_LAB_GetInputBuffer_covmock_get_input_buffer_allocates(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_GetInputBuffer_covmock_Register(void)
{
    UtTest_Add(CI_LAB_GetInputBuffer_covmock_get_input_buffer_allocates, CI_LAB_GetInputBuffer_covmock_Setup, NULL, "get_input_buffer_allocates");
}

// covmock case: get_input_buffer_allocates
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_passthru_decode.c:47 (line, line_executed)
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_passthru_decode.toml:1 covmock:test get_input_buffer_allocates
// confidence: medium
// manifest id: ce1819b382f0b79e44ddd50593536656
// spec id: a863d8aeda9225c2c9deab5dfd7439c6
static void CI_LAB_GetInputBuffer_covmock_get_input_buffer_allocates(void)
{
    void * Buffer = {0};
    size_t Size = {0};

    // act
    CFE_Status_t covmock_result = CI_LAB_GetInputBuffer(&Buffer, &Size);
    (void)covmock_result;

    // assert
    UtAssert_True((UT_GetStubCount(UT_KEY(CFE_SB_AllocateMessageBuffer))) == (1), "%s", "UT_GetStubCount(UT_KEY(CFE_SB_AllocateMessageBuffer)) == 1");
}
