// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=d8cf2cce42277b4298da0e6869831f73 file=tests/test_CI_LAB_DecodeInputMessage.c
// Put manual extensions outside this directory; it is disposable.

// A UT Assert program has exactly one UtTest_Setup, and covmock writes one case file per callable under test, so this file does not define one -- a second file would be a duplicate symbol.
// Register these cases from the UtTest_Setup your project owns:
//
//     void CI_LAB_DecodeInputMessage_covmock_Register(void);
//     void UtTest_Setup(void) { CI_LAB_DecodeInputMessage_covmock_Register(); }

#include "utassert.h"
#include "uttest.h"
#include "cfe.h"
#include "ci_lab_app.h"
#include "ci_lab_perfids.h"
#include "ci_lab_msgids.h"
#include "ci_lab_decode.h"
#include "mocks/mock_cfs_utstub.h"

#include "apps/ci_lab/fsw/src/ci_lab_decode.h"

// Run before each case, with the report context set to TSF: an assertion that fails in here is recorded as a Test Setup Failure rather than as a test failure.
static void CI_LAB_DecodeInputMessage_covmock_Setup(void)
{
    // no per-case arrangement state to reset
}

static void CI_LAB_DecodeInputMessage_covmock_short_packet_is_rejected(void);

// UT Assert copies a registered name into char[OS_MAX_API_NAME * 2] and truncates it, so each case is registered under its own name alone. The group is this file.
void CI_LAB_DecodeInputMessage_covmock_Register(void)
{
    UtTest_Add(CI_LAB_DecodeInputMessage_covmock_short_packet_is_rejected, CI_LAB_DecodeInputMessage_covmock_Setup, NULL, "short_packet_is_rejected");
}

// covmock case: short_packet_is_rejected
// review state: reviewed
// coverage gap: apps/ci_lab/fsw/src/ci_lab_passthru_decode.c:84 (line, line_executed)
// condition: SourceSize < sizeof ( CFE_MSG_CommandHeader_t )
// specified by: sidecar apps/ci_lab/unit-test/annotations/ci_lab_passthru_decode.toml:2 covmock:test short_packet_is_rejected
// confidence: medium
// manifest id: d8cf2cce42277b4298da0e6869831f73
// spec id: 6434ff8a53ddac5b09888569a9b8bb09
static void CI_LAB_DecodeInputMessage_covmock_short_packet_is_rejected(void)
{
    CFE_SB_Buffer_t * Out = {0};

    // act
    CFE_Status_t covmock_result = CI_LAB_DecodeInputMessage(NULL, 0, &Out);
    (void)covmock_result;

    // assert
    UtAssert_True((covmock_result) == (CFE_STATUS_WRONG_MSG_LENGTH), "%s", "covmock_result == CFE_STATUS_WRONG_MSG_LENGTH");
}
