// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=886fd2488093e8ec40a294f3b14b11b3 file=mocks/mock_cfs_utstub.c
// Put manual extensions outside this directory; it is disposable.

// covmock: CFE_EVS_SendEvent already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_TimeStampMsg already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).
// covmock: CFE_SB_TransmitMsg already has a cFS stub in this project; no definition is emitted for it (a second one would be a duplicate symbol at link time).

#include "apps/ci_lab/fsw/src/ci_lab_app.h"
#include "cfe/modules/core_api/fsw/inc/cfe_sb.h"
#include "utgenstub.h"

// covmock: generated stub for CI_LAB_ReadUpLink()
void CI_LAB_ReadUpLink(void)
{
    UT_GenStub_Execute(CI_LAB_ReadUpLink, Basic, NULL);
}

// covmock: generated stub for CI_LAB_ResetCounters_Internal()
void CI_LAB_ResetCounters_Internal(void)
{
    UT_GenStub_Execute(CI_LAB_ResetCounters_Internal, Basic, NULL);
}

// covmock: output-parameter handler for CFE_SB_TimeStampMsg(); a test installs it
// with UT_SetHandlerFunction and supplies the value with UT_SetDataBuffer.
void UT_Handler_CFE_SB_TimeStampMsg(void *UserObj, UT_EntryKey_t FuncKey,
                                    const UT_StubContext_t *Context)
{
    CFE_MSG_Message_t *MsgPtr = UT_Hook_GetArgValueByName(Context, "MsgPtr", CFE_MSG_Message_t *);

    (void)UserObj;
    (void)FuncKey;

    if (MsgPtr != NULL)
    {
        UT_Stub_CopyToLocal(UT_KEY(CFE_SB_TimeStampMsg), MsgPtr, sizeof(*MsgPtr));
    }
}
