// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=66f38c8918a1c789876e11fcb5103c49 file=mocks/mock_cfs_utstub.h
// Put manual extensions outside this directory; it is disposable.

#ifdef __cplusplus
extern "C" {
#endif

#include "apps/ci_lab/fsw/src/ci_lab_app.h"
#include "cfe/modules/core_api/fsw/inc/cfe_evs.h"
#include "cfe/modules/core_api/fsw/inc/cfe_sb.h"
#include "utstubs.h"

// covmock: a cFS stub is a definition of the production prototype, so
// nothing is declared here -- the production header above already
// declares every stubbed function, and utstubs.h supplies
// UT_KEY() and the UT_Set*/UT_Get* control API a test arranges with.

#ifdef __cplusplus
}  // extern "C"
#endif
