// Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
// covmock:generated tool=covmock/0.1.0.dev0 manifest=886fd2488093e8ec40a294f3b14b11b3 file=mocks/mock_cfs_utstub.h
// Put manual extensions outside this directory; it is disposable.

#ifdef __cplusplus
extern "C" {
#endif

#include "apps/ci_lab/fsw/src/ci_lab_app.h"
#include "cfe/modules/core_api/fsw/inc/cfe_evs.h"
#include "cfe/modules/core_api/fsw/inc/cfe_sb.h"
#include "utstubs.h"

// covmock: a cFS stub is a definition of the production prototype, so
// nothing is declared here -- the production header above already
// declares every stubbed function, and utstubs.h supplies
// UT_KEY() and the UT_Set*/UT_Get* control API a test arranges with.

// covmock: the output-parameter handlers (#100). A generated stub copies
// nothing out of a data buffer by itself -- the copy happens in a handler --
// so the arrangement installs one of these, and it is declared here because
// the arrangement is written in the test's translation unit, not in the mock's.
void UT_Handler_CFE_SB_TimeStampMsg(void *UserObj, UT_EntryKey_t FuncKey, const UT_StubContext_t *Context);

#ifdef __cplusplus
}  // extern "C"
#endif
