# Generated by covmock 0.1.0.dev0. Do not edit: regenerating overwrites it.
# covmock:generated tool=covmock/0.1.0.dev0 manifest=66f38c8918a1c789876e11fcb5103c49 file=covmock.cmake
# Put manual extensions outside this directory; it is disposable.

# This fragment attaches covmock's generated sources to a target you
# already own. It defines variables and one function, creates no
# targets, downloads nothing, and changes no global setting.
#
#     include(${CMAKE_CURRENT_LIST_DIR}/covmock.cmake)
#     covmock_add_to_target(<your existing test target>)
#
# Several covmock output directories may be used from one CMakeLists
# -- one per test runner -- as long as each include is followed by its
# own covmock_add_to_target() call: including a fragment sets the variables
# that call reads.
#
# Everything in this directory is generated and disposable. Keep manual
# extensions outside it.

set(COVMOCK_GENERATED_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(COVMOCK_MOCK_SOURCES)
set(COVMOCK_TEST_SOURCES
  "${COVMOCK_GENERATED_DIR}/tests/test_CI_LAB_NoopCmd.c"
  "${COVMOCK_GENERATED_DIR}/tests/test_CI_LAB_ReadUplinkCmd.c"
  "${COVMOCK_GENERATED_DIR}/tests/test_CI_LAB_ResetCountersCmd.c"
  "${COVMOCK_GENERATED_DIR}/tests/test_CI_LAB_SendHkCmd.c"
)
set(COVMOCK_INCLUDE_DIRECTORIES
  "${COVMOCK_GENERATED_DIR}/."
  "${COVMOCK_GENERATED_DIR}/../../../../.."
  "${COVMOCK_GENERATED_DIR}/mocks"
  "${COVMOCK_GENERATED_DIR}/tests"
)

# Attach the generated sources to an existing target.
# The target, its language standard, its warning flags and its link
# line stay the caller's.
function(covmock_add_to_target covmock_target)
  if(NOT TARGET ${covmock_target})
    message(FATAL_ERROR "covmock: ${covmock_target} is not a target. Call covmock_add_to_target() with a target you have already defined.")
  endif()
  target_sources(${covmock_target} PRIVATE
    ${COVMOCK_MOCK_SOURCES}
    ${COVMOCK_TEST_SOURCES}
  )
  target_include_directories(${covmock_target} PRIVATE ${COVMOCK_INCLUDE_DIRECTORIES})

  # The cFS UT Assert library is supplied by the project's own build.
  # covmock never downloads, fetches or configures a dependency.
  # cFS's add_cfe_coverage_test() already links it, with the plain
  # target_link_libraries() signature -- and CMake refuses a keyword
  # call on a target that has used the plain one -- so a target that
  # already links ut_assert is left exactly as it is.
  get_target_property(covmock_linked ${covmock_target} LINK_LIBRARIES)
  if(NOT covmock_linked)
    set(covmock_linked)
  endif()
  list(FIND covmock_linked "ut_assert" covmock_has_ut_assert)
  if(NOT covmock_has_ut_assert EQUAL -1)
    # already linked by the project
  elseif(TARGET ut_assert)
    target_link_libraries(${covmock_target} PRIVATE ut_assert)
  else()
    message(WARNING "covmock: no ut_assert target was found; link the covmock test target against the cFS UT Assert library yourself. covmock does not fetch dependencies.")
  endif()
  # Each generated case file exposes one registration function and no
  # UtTest_Setup, because a UT Assert program may have only one of
  # those and covmock may have written several files. Grep the
  # generated cases for '_Register(void)' and call each one from the
  # UtTest_Setup your test program owns.
endfunction()
